<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
Schema::create('companies',fn(Blueprint $t)=>[$t->id(),$t->string('name')->unique(),$t->string('type')->nullable(),$t->text('remarks')->nullable(),$t->timestamps()]);
Schema::create('projects',fn(Blueprint $t)=>[$t->id(),$t->string('name')->unique(),$t->string('code')->nullable(),$t->string('location')->nullable(),$t->string('status')->default('active'),$t->text('remarks')->nullable(),$t->timestamps()]);
Schema::create('designations',fn(Blueprint $t)=>[$t->id(),$t->string('name')->unique(),$t->text('remarks')->nullable(),$t->timestamps()]);
Schema::create('employees',function(Blueprint $t){$t->id();$t->string('employee_code')->nullable()->unique();$t->string('name')->index();$t->string('normalized_name')->index();$t->string('iqama_no')->nullable()->unique();$t->string('passport_no')->nullable()->index();$t->foreignId('designation_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('company_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('current_project_id')->nullable()->constrained('projects')->nullOnDelete();$t->string('shift')->nullable();$t->string('accommodation')->nullable();$t->date('doj')->nullable();$t->string('phone')->nullable();$t->decimal('hourly_rate',12,2)->nullable();$t->decimal('monthly_salary',12,2)->nullable();$t->string('status')->default('active');$t->text('remarks')->nullable();$t->string('source_sheet')->nullable();$t->timestamps();});
Schema::create('employee_project_assignments',function(Blueprint $t){$t->id();$t->foreignId('employee_id')->constrained()->cascadeOnDelete();$t->foreignId('project_id')->constrained()->cascadeOnDelete();$t->date('start_date')->nullable();$t->date('end_date')->nullable();$t->string('status')->default('active');$t->text('remarks')->nullable();$t->timestamps();});
Schema::create('attendance_months',function(Blueprint $t){$t->id();$t->foreignId('project_id')->nullable()->constrained()->nullOnDelete();$t->unsignedTinyInteger('month');$t->unsignedSmallInteger('year');$t->string('source_file')->nullable();$t->string('source_sheet')->nullable();$t->foreignId('imported_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('imported_at')->nullable();$t->timestamps();});
Schema::create('attendance_records',function(Blueprint $t){$t->id();$t->foreignId('employee_id')->constrained()->cascadeOnDelete();$t->foreignId('project_id')->nullable()->constrained()->nullOnDelete();$t->date('attendance_date')->index();$t->unsignedTinyInteger('month');$t->unsignedSmallInteger('year');$t->string('status')->default('empty')->index();$t->decimal('hours',8,2)->nullable();$t->string('raw_value')->nullable();$t->boolean('is_extra_duty')->default(false);$t->string('extra_duty_type')->nullable();$t->decimal('extra_duty_hours',8,2)->nullable();$t->decimal('extra_duty_amount',12,2)->nullable();$t->text('remarks')->nullable();$t->string('source_sheet')->nullable();$t->timestamps();$t->unique(['employee_id','attendance_date','project_id'],'att_unique');});
Schema::create('advance_payments',function(Blueprint $t){$t->id();$t->foreignId('employee_id')->constrained()->cascadeOnDelete();$t->foreignId('project_id')->nullable()->constrained()->nullOnDelete();$t->decimal('amount',12,2);$t->date('payment_date')->nullable();$t->string('payment_type')->default('manual');$t->string('source_sheet')->nullable();$t->text('remarks')->nullable();$t->timestamps();});
Schema::create('extra_duties',function(Blueprint $t){$t->id();$t->foreignId('employee_id')->constrained()->cascadeOnDelete();$t->foreignId('project_id')->nullable()->constrained()->nullOnDelete();$t->date('duty_date');$t->string('day_type')->default('normal_day');$t->decimal('hours_worked',8,2);$t->decimal('rate',12,2)->default(0);$t->decimal('amount',12,2)->default(0);$t->string('approval_status')->default('pending');$t->foreignId('approved_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('approved_at')->nullable();$t->text('remarks')->nullable();$t->string('source_sheet')->nullable();$t->timestamps();});
Schema::create('payslips',function(Blueprint $t){$t->id();$t->foreignId('employee_id')->constrained()->cascadeOnDelete();$t->foreignId('project_id')->nullable()->constrained()->nullOnDelete();$t->unsignedTinyInteger('month');$t->unsignedSmallInteger('year');$t->decimal('total_hours',10,2)->default(0);$t->decimal('normal_hours',10,2)->default(0);$t->decimal('extra_duty_hours',10,2)->default(0);$t->unsignedSmallInteger('days_worked')->default(0);$t->unsignedSmallInteger('absent_days')->default(0);$t->decimal('hourly_rate',12,2)->nullable();$t->decimal('monthly_salary',12,2)->nullable();$t->decimal('normal_salary',12,2)->default(0);$t->decimal('extra_duty_amount',12,2)->default(0);$t->decimal('gross_salary',12,2)->default(0);$t->decimal('advance_deduction',12,2)->default(0);$t->decimal('net_salary',12,2)->default(0);$t->foreignId('generated_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('generated_at')->nullable();$t->string('status')->default('draft');$t->timestamps();});
Schema::create('generated_reports',function(Blueprint $t){$t->id();$t->string('report_type');$t->string('report_name');$t->foreignId('project_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('employee_id')->nullable()->constrained()->nullOnDelete();$t->unsignedTinyInteger('month')->nullable();$t->unsignedSmallInteger('year')->nullable();$t->json('filters')->nullable();$t->string('file_type');$t->string('file_path');$t->foreignId('generated_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('generated_at')->nullable();$t->string('status')->default('completed');$t->timestamps();});
Schema::create('imports',function(Blueprint $t){$t->id();$t->string('import_type');$t->string('file_name');$t->foreignId('project_id')->nullable()->constrained()->nullOnDelete();$t->unsignedTinyInteger('month')->nullable();$t->unsignedSmallInteger('year')->nullable();$t->foreignId('imported_by')->nullable()->constrained('users')->nullOnDelete();$t->unsignedInteger('total_rows')->default(0);$t->unsignedInteger('success_rows')->default(0);$t->unsignedInteger('failed_rows')->default(0);$t->string('status')->default('completed');$t->text('remarks')->nullable();$t->timestamps();});
}public function down():void{foreach(['imports','generated_reports','payslips','extra_duties','advance_payments','attendance_records','attendance_months','employee_project_assignments','employees','designations','projects','companies'] as $x)Schema::dropIfExists($x);}};
